name: Issues workflow
on: issues
jobs:
  print-events:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3
    - name: print events
      uses: echo "{{ github.event }}"



  